@startuml
title fmri Pipeline 2-nd level analysis with DoRs analytics

start

:Prepare 2-nd Level Analysis SPM runs;
repeat
:Define 2 groups with "Gesunde" and "Patienten";
repeat
:Load "Gesunde" DoRs in group1;
:Load "Patienten" DoRs in group2; 
repeat while (all subjects) is (repeat this for all subjects)
:Run and create SPM.mat;
:Perform SPM Estimate of SPM.mat;
:define 4 different T-contrasts;
:masking = none, threshold 0.005 voxels 50;
:Perform Result of SPM.mat;
repeat while (for all condition DoRs) is (repeat this for all 8 conditions)
:Use SPM and xjview to visualize the results;
stop
@enduml  